apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 1e5b953f-3f65-4144-ae8a-257a9e21acc8
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: watch-list-exists-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /watch_list/variable_income/exists
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /watch_list/variable_income/exists
